# Generated by Django 2.2.24 on 2021-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211224_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_shot',
            field=models.URLField(blank=True, null=True, verbose_name='Screenshot'),
        ),
    ]
