# Generated by Django 2.2.24 on 2021-12-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211225_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.TextField(choices=[('Django', 'Django'), ('React Native', 'React Native')]),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.TextField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')]),
        ),
    ]
