# Generated by Django 2.2.24 on 2021-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211225_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen_shot',
            field=models.URLField(blank=True, verbose_name='Screenshot'),
        ),
    ]
