# Generated by Django 2.2.24 on 2021-12-25 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211225_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='subscription',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='app_subscription', to='home.Subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
