# Generated by Django 2.2.24 on 2021-12-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211225_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='subscription',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_subscription', to='home.Subscription'),
        ),
    ]
