# Generated by Django 2.2.24 on 2021-12-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211225_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='subscription',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_subscription', to='home.Subscription'),
        ),
        migrations.AlterField(
            model_name='app',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
