# Generated by Django 2.2.24 on 2021-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211225_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='screen_shot',
            field=models.URLField(blank=True, editable=False, verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
