# Generated by Django 2.2.24 on 2021-12-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211225_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_app', to='home.App'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='home.Plan'),
        ),
    ]
