# Generated by Django 2.2.24 on 2021-12-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211228_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='subscription',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_subscription', to='home.Subscription'),
        ),
    ]
